# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import lememe.models


class Migration(migrations.Migration):

    dependencies = [
        ('lememe', '0002_auto_20190217_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=lememe.models.get_post_image_folder, verbose_name='Image'),
        ),
    ]
