# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import lememe.models
import lememe.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lememe', '0003_auto_20190217_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, storage=lememe.storage.OverwriteStorage(), upload_to=lememe.models.get_post_image_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, storage=lememe.storage.OverwriteStorage(), upload_to=lememe.models.get_user_image_folder, verbose_name='Profile picture'),
        ),
    ]
