# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lememe', '0004_auto_20190217_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
